@startuml

class Event {

}

class EventAlert {

}

class EventReport {
}

class EventOperator {

}


class Equipment {

}

class Procedure {

}


class Action {

}

class Service {

}

class TodoAction {
}

class EquipmentEntity {
}

class Family {
}

class Domain {
}





Event <|-- EventAlert
Event <|-- EventReport
Event <|-- EventOperator

Event "1" -- "1" Domain: has

Event "1" -- "0..1" Equipment: Is linked to

Event "1..n" -- "0..1" Procedure: Contains

Procedure "1" -- "0..n" Action: Contains
Equipment "1" -- "0..n" Service: Contains
Equipment "1" -- "1" EquipmentEntity: has
Equipment "1" -- "1" Family: has

Action <|-- Service
Action <|-- TodoAction




@enduml