= A guide for new contributors

== Install Environment

The required languages and tools to work on the project are specified in the `.tools_version` file in the root folder.

Nonetheless, *docker* or *podman* must be available in your environment

* Docker v.*20*

`asdf` related documentation can be found xref:provoly-doc:processus:outils.adoc[here]

== IntelliJ Setup

Open the Preferences window (or Settings depending on your edition), navigate to Plugins and install the Adapter for Eclipse Code Formatter from the Marketplace.

Restart your IDE, open the Preferences (or Settings) window again and navigate to Adapter for Eclipse Code Formatter section on the left pane.

Select Use Eclipse's Code Formatter, then change the Eclipse workspace/project folder or config file to point to the eclipse-format.xml file in the independent-projects/ide-config/src/main/resources directory. Make sure the Optimize Imports box is ticked. Then, select Import Order from file and make it point to the eclipse.importorder file in the ide-config/src/main/resources directory.

Next, disable wildcard imports: navigate to `Editor` -> `Code Style` -> `Java` -> `Imports` and set `Class count to use import with '\*'` to 5. Do the same with `Names count to use static import with '*'`.


=== AsciiDoc

Our technical documentation uses the plain text markup language *AsciiDoc*.

In order to visualize your changes in the documentation, you will require the `AsciiDoc` plugin from the marketplace.

After that, you have to enable *soft wraps* for the asciiDoc files : `general` -> `editor` -> `softwrap` -> *.adoc


=== SonarLint
Extension which finds and fixes coding issues in real-time.

=== Run the formatter manually

The following command must be run in the root folder.

[source,bash]
----
mvn compile
----

When submitting a merge request the CI build will fail if the code isn't properly formatted, so it is recommended that you always run a full Maven build before submitting a pull request.

== Architecture documentation

The architecture documentation uses https://docs.structurizr.com/[Structurizr].

An extended documentation can be found https://docs.structurizr.com/dsl/cookbook/[here].

Simply run :

[source,bash]
----
docker run --rm -v ./docs/structurizr:/usr/local/structurizr -p 9191:8080 structurizr/lite:2024.01.02
----

As of now, exporting as svg is done as described https://docs.structurizr.com/ui/diagrams/export[here]

As of now, no roles are specified, but this is subject to change in the future.

== Deploy new stream module

* update the parent `pom.xml` by adding the new module name
* update `IMAGES_MAP` variable in `.github/update_values.yaml` by adding the module name and its image name.