name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:

env:
  JAVA_VERSION: 21
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.showDateTime=true -Djansi.force=true"
  MAVEN_CLI_OPTS: "-Dstyle.color=always --batch-mode --errors --show-version -DinstallAtEnd=true -Dno-format -DdeployAtEnd=true"
  MAVEN_JIB_OPTIONS: "-Dquarkus.container-image.labels.\"git-ref\"=${{ github.sha }} -Djib.serialize=true"
  IGNORED_FOLDERS: ". .github docs"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  pre_job:
    name: Preparing path-ignores
    runs-on: provoly-runner
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          paths_ignore: '["**/.gitignore","LICENSE","**/*.adoc","**/*.txt","docs/**", "**/ide-config", ".github/**", "pom.xml", ".tool-versions"]'
          do_not_skip: '["workflow_dispatch"]'
          skip_after_successful_duplicate: false

  module-matrix:
    name: Detect changed modules
    runs-on: provoly-runner
    outputs:
      modules: ${{ steps.modules.outputs.matrix }}
    steps:
      - name: Install requests lib
        run: sudo apt update && sudo apt install python3-requests -y
      - name: Get modules
        id: modules
        env:
          NEO_LOG_LEVEL: DEBUG
        uses: hellofresh/action-changed-files@v3
        with:
          pattern: (?P<module>(?!docs)[^/\.]+)/

  build:
    strategy:
      matrix: ${{ fromJson(needs.module-matrix.outputs.modules) }}
    if: ${{  fromJson(needs.module-matrix.outputs.modules).include[0] }}  # if no module changes do nothing
    name: "Build ${{ matrix.module }}"
    runs-on: provoly-runner
    needs:
      - module-matrix
    steps:
      - uses: actions/checkout@v4

      - name: Echo
        run: echo ${{ matrix.module }}

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Sets env vars for main branch
        run: |
          export CI_SHORT_COMMIT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8) >> $GITHUB_ENV
          echo CI_SHORT_COMMIT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8) >> $GITHUB_ENV
          export "DOCKER_IMAGE_ADDITIONAL_TAGS=dev-$CI_SHORT_COMMIT_SHA,latest" >> $GITHUB_ENV
          echo "MAVEN_CLI_OPTS=-Dstyle.color=always --batch-mode --errors --show-version -DinstallAtEnd=true -DdeployAtEnd=true -Dquarkus.container-image.additional-tags=$DOCKER_IMAGE_ADDITIONAL_TAGS -Dquarkus.container-image.labels.\"git-ref\"=$CI_SHORT_COMMIT_SHA -DskipTests" >> $GITHUB_ENV
          echo "MAVEN_PROFILE=-Pdocker-image" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/main'

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: provoly-maven-${{ hashFiles('${{ matrix.module }}/pom.xml') }}
          restore-keys: |
            provoly-maven-

      - name: Build with Maven
        run: mvn ${{ env.MAVEN_JIB_OPTIONS }} ${{ env.MAVEN_CLI_OPTS }} verify -pl ${{ matrix.module }} ${{ env.MAVEN_PROFILE }}
        env:
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          REGISTRY_URL: ${{ vars.REGISTRY_URL }}
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PROJECT_NAME: provoly

      - name: Update values on chalons-dev
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_DISPATCH_TOKEN }}
          repository: provoly/provoly-chart-values
          event-type: update-chart-value
          client-payload: |
            {
              "filename": "chalons/chalons-dev/provoly/values.yaml",
              "field_names": "${{ matrix.module }}",
              "field_value": "dev-${{ env.CI_SHORT_COMMIT_SHA }}"
            }
