name: "Update ArgoCD values."

on:
  workflow_call:
    inputs:
      fieldName:
        description: 'fieldName'
        required: true
        type: string
      fieldValue:
        description: 'fieldName'
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: provoly-runner
    steps:
      - uses: actions/checkout@v4
      - name: Update values on chalons-dev
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_DISPATCH_TOKEN }}
          repository: provoly/provoly-chart-values
          event-type: update-chart-value
          client-payload: |
            {
              "filename": "chalons/chalons-dev/provoly/values.yaml",
              "field_names": ${{ inputs.fieldName }}
              "field_value": "dev-${{ inputs.fieldValue }}"
            }
        if: github.ref == 'refs/heads/main'
