<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>coverage</artifactId>
    <packaging>pom</packaging>
    <version>0.1.0</version>
    <parent>
        <groupId>com.provoly</groupId>
        <artifactId>parent</artifactId>
        <version>0.1.0</version>
        <relativePath>../parent</relativePath>
    </parent>


    <dependencies>
        <dependency>
            <groupId>com.provoly</groupId>
            <artifactId>stream-camera-comptage</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.provoly</groupId>
            <artifactId>stream-consumption-per-day</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.provoly</groupId>
            <artifactId>stream-equipment-enriched</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.12</version>
                <executions>
                    <execution>
                        <id>report-aggregate</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>report-aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>